services:
  frontend:
    image: ghcr.io/metgag/loket:fe.v16
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    image: ghcr.io/metgag/loket-be:v14
    ports:
      - 6011:6011
    volumes:
      - ./weekly/public:/app/public
      - ./.env:/app/.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:17.6-alpine3.22
    env_file: ./.env
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - 5433:5432
  redis:
    image: redis:alpine
    env_file: ./.env
    volumes:
      - redis_dat:/data
    ports:
      - 6379:6379

volumes:
  pg:
    external: true
  redis_dat:
    external: true