name: Build and publish Docker Tickitz Backend to ghcr.io
on: [push]
jobs:
    tickitz_api_publish:
        runs-on: ubuntu-22.04
        steps:
            - run: echo "Building image for ${{ github.repository }}."
            - name: Checkout repository code
              uses: actions/checkout@v5
            - name: Build and publish a Docker image for ${{ github.repository }}
              uses: macbre/push-to-ghcr@master
              with:
                image_name: ${{ github.repository }}
                github_token: ${{ secrets.GITHUB_TOKEN }}